services:
  fe:
    image: nginx:alpine
    container_name: pskhome-fe
    restart: unless-stopped
    ports:
      - 5173:80
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
          listen       80;
          server_name  localhost;
          root         /usr/share/nginx/html;

          location / {
            try_files /\$$uri /index.html;
            index index.html;
          }
        }
        EOF
        nginx -g 'daemon off;'
