name: database

networks:
  default:
    external: true
    name: traefik

volumes:
  db:

services:
  mem:
    image: redis:alpine
    container_name: pskhome-mem-1
    restart: unless-stopped
    ports:
      - 6379:6379
    tmpfs:
      - /data

  db:
    image: mysql:8.0
    container_name: pskhome-db-1
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_EXPIRE_LOGS_DAYS: 7
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: page
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql
      - ../connection:/var/run/mysqld
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
