name: Front-End Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

        # 2. Node.js 22 설치
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. npm install
      - name: Install modules
        working-directory: frontend
        run: npm install

        # 4. npm run build
      - name: Build
        working-directory: frontend
        run: npm run build

        # 5. Copy dist
      - name: Copy dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend/dist/, server/
          target: ~/${{ github.event.repository.name }}

      # 5. SSH 서버 접근 테스트
      # - name: SSH server access test
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/elfaka.kr.pem
      #     chmod 600 ~/.ssh/elfaka.kr.pem
      #     ssh-keyscan -p 2222 ssh.elfaka.kr >> ~/.ssh/known_hosts
      #     ssh -i ~/.ssh/elfaka.kr.pem -p 2222 qkrtjsrb312@ssh.elfaka.kr "echo 'SSH connection successful'"
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 6. 기존 dist 폴더 삭제 및 새로운 dist 폴더 업로드
      # - name: Replace dist folder on server
      #   run: |
      #     ssh -i ~/.ssh/elfaka.kr.pem -p 2222 qkrtjsrb312@ssh.elfaka.kr "rm -rf /home/qkrtjsrb312/PskHome/dist"
      #     scp -P 2222 -i ~/.ssh/elfaka.kr.pem -r ./frontend/dist qkrtjsrb312@ssh.elfaka.kr:/home/qkrtjsrb312/PskHome/dist
